packages:
  - docs
  - playground
  - apps/**
  - packages/**
  - examples/*
catalog:
  '@alova/adapter-uniapp': ^2.0.11
  '@alova/shared': ^1.1.2
  '@uni-helper/vite-plugin-uni-layouts': ^0.1.10
  '@iconify-json/carbon': ^1.1.37
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.10.6
  '@unocss/preset-web-fonts': ^0.64.0
  '@unocss/core': ^0.64.0
  '@unocss/preset-mini': ^0.64.0
  '@unocss/preset-icons': ^0.64.0
  '@vitejs/plugin-vue': ^5.1.4
  '@vueuse/core': ^11.2.0
  '@dcloudio/uni-app': 3.0.0-4040520250104002
  '@dcloudio/uni-app-harmony': 3.0.0-4040520250104002
  '@dcloudio/uni-app-plus': 3.0.0-4040520250104002
  '@dcloudio/uni-components': 3.0.0-4040520250104002
  '@dcloudio/uni-h5': 3.0.0-4040520250104002
  '@dcloudio/uni-mp-alipay': 3.0.0-4040520250104002
  '@dcloudio/uni-mp-baidu': 3.0.0-4040520250104002
  '@dcloudio/uni-mp-jd': 3.0.0-4040520250104002
  '@dcloudio/uni-mp-kuaishou': 3.0.0-4040520250104002
  '@dcloudio/uni-mp-lark': 3.0.0-4040520250104002
  '@dcloudio/uni-mp-qq': 3.0.0-4040520250104002
  '@dcloudio/uni-mp-toutiao': 3.0.0-4040520250104002
  '@dcloudio/uni-mp-weixin': 3.0.0-4040520250104002
  '@dcloudio/uni-mp-xhs': 3.0.0-4040520250104002
  '@dcloudio/uni-quickapp-webview': 3.0.0-4040520250104002
  '@vue/shared': 3.5.13
  '@dcloudio/types': ^3.4.12
  '@dcloudio/uni-automator': 3.0.0-4040520250104002
  '@dcloudio/uni-cli-shared': 3.0.0-4040520250104002
  '@dcloudio/uni-stacktracey': 3.0.0-4040520250104002
  '@dcloudio/vite-plugin-uni': 3.0.0-4040520250104002
  '@egoist/tailwindcss-icons': ^1.8.2
  '@icebreakers/eslint-config': ^0.7.12
  '@icebreakers/stylelint-config': ^0.1.3
  '@iconify-json/mdi': ^1.2.2
  '@iconify-json/svg-spinners': ^1.2.2
  '@vue/runtime-core': 3.5.13
  jsencrypt: ^3.3.2
  alova: ^3.2.9
  autoprefixer: ^10.4.20
  wot-design-uni: ^1.7.1
  eslint: ^9.18.0
  postcss: ^8.5.1
  sass: ^1.83.4
  tailwindcss: ^3.4.17
  unplugin-auto-import: ^0.19.0
  vite: 5.2.8
  weapp-ide-cli: ^2.0.9
  weapp-tailwindcss: ^3.7.0
  pinia: ^2.3.0
  vue: 3.5.13
  vue-i18n: ^9.14.2
  magic-color: ^2.0.0
  element-plus: ^2.8.7
  unplugin-vue-components: ^0.27.4
  unplugin-element-plus: ^0.8.0
  vue-tsc: ^2.1.10
  unocss: ^0.64.0
  unocss-transformer-alias: ^0.0.8
  bumpp: ^9.5.2
  consola: ^3.2.3
  esno: ^4.7.0
  execa: ^8.0.1
  fs-extra: ^11.2.0
  lint-staged: ^15.2.9
  ofetch: ^1.3.4
  pathe: ^1.1.2
  simple-git: ^3.25.0
  floating-vue: ^5.2.2
  simple-git-hooks: ^2.11.1
  std-env: ^3.7.0
  taze: ^0.16.6
  typescript: ^5.7.3
  unbuild: ^2.0.0
  vitepress: ^1.3.3
  vitepress-plugin-group-icons: ^1.0.3
  vitest: ^2.0.5
  vue-flow-layout: ^0.1.1
  vite-plugin-dts: ^4.3.0
